# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb00a4f542d760128d0c0b488d48117567b0fe561f6f07519392b362330a6cc2151e0d5d04db6dacad4e1c35daec984de7bce1485f32942f3ff27e1f579f3b49

test:
  secret_key_base: cc0d088df61547c53693754fa75f6387667674fa5480d20eb4ea2b3090b7f0e4125f24d8e068b06d5093df159fc485bf0ee94537dc68d2069a1bf62b2bc0a42e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
